### PR TITLE
Css fix

### PR DESCRIPTION
**Pull request by chloeleichen**
css fixes:
screen shot 2016-08-26 at 9 32 00 am
screen shot 2016-08-26 at 9 32 58 am
screen shot 2016-08-26 at 9 33 41 am
screen shot 2016-08-26 at 9 37 46 am
screen shot 2016-08-26 at 9 38 25 am

And this one requires https://github.com/TerriaJS/terriajs/pull/1991 to be merged: 

screen shot 2016-08-26 at 9 35 24 am

### CODE REVIEW

**Comment by RacingTadpole** [comment]
The lat/lon/elev is off the bottom of the screen for me now?
image

**Comment by RacingTadpole** [comment]
The logo is now too small I think - compare:
nationalmap.gov.au/northernaustralia:
image
vs this PR:
image

**Comment by RacingTadpole** [comment]
We've also lost that "back" link off the bottom of the lefthand panel completely?
image

**Comment by RacingTadpole** [comment]
The feature info is better, but still a bit tight... not urgent, but if it's easy
image

**Comment by RacingTadpole** [comment]
that's all from me!

**Comment by chloeleichen** [comment]
Done, can you check again please 😄  @RacingTadpole

**Comment by RacingTadpole** [comment]
thanks Chloe! This is perfect.

**Pull request merged**
